---
language: go

sudo: false

go:
  - 1.7

services:
  - rabbitmq

branches:
  only:
    - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count
  - goveralls -service=travis-ci
