---
language: go

sudo: false

go:
  - 1.7

services:
  - rabbitmq

branches:
  only:
    - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=profile.cov
  - goveralls -coverprofile=profile.cov -service=travis-ci
